### ISSUE TITLE
Image not proper and content also matched with figma

### ISSUE THREAD

**Issue by jeyabaskar2** [s-niwas/figmaland#1]
<img width="1439" alt="image" src="https://github.com/s-niwas/figmaland/assets/108126227/109eec21-b705-45e4-b33a-a15e7179cc2b">

Figma

<img width="701" alt="image" src="https://github.com/s-niwas/figmaland/assets/108126227/692f8d48-7b2a-4b7d-a5b6-3ae5381899eb">

**Comment by ghost** [comment]
corrected the image
