### ISSUE TITLE
Gallery section not matching with figma

### ISSUE THREAD

**Issue by jeyabaskar2** [s-niwas/figmaland#3]
<img width="1424" alt="image" src="https://github.com/s-niwas/figmaland/assets/108126227/afb41051-8e09-4186-880c-bd9fae180f78">

Figma
<img width="870" alt="image" src="https://github.com/s-niwas/figmaland/assets/108126227/7d3e565c-09aa-46d5-a415-51862a7b3b05">

**Comment by ghost** [comment]
corrected
